# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration-ui

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '**/appconfig.json'
      env:
        integrationApiEndpoint: "qa"
        cpssApiEndpoint: "qa"
    - run: npm install
    - run: npm run format
    - run: npm run prettier-format
    - run: npm run build 

  deployment:
    runs-on: windows-latest
    environment: Dev
    steps:
     - name: Azure Login
       uses: Azure/login@v1.4.4
       with:
        client-id: 086a0664-ed97-4ab8-ad5a-e464cf08e907
        tenant-id: ce235d14-4b96-4b29-888d-073a6bd1ab58
        subscription-id: 41769997-21d3-41c1-b8d9-51d728e84b03
 
     

    
      
 
    
